<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PRAKRUTI-UNGAMJI" failures="23" tests="34" name="Test" time="49.104" errors="0" timestamp="2024-03-20T15:24:40 IST">
  <testcase classname="testcases.Money_Control_L1_TestCases" name="verifyNavigateToHomePage" time="0.037">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.verifyNavigateToHomePage(Money_Control_L1_TestCases.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyNavigateToHomePage -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="click_Shop_Menu" time="3.792"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="navigate_to_Shop_page" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.navigate_to_Shop_page(Money_Control_L1_TestCases.java:100)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigate_to_Shop_page -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="click_on_cart" time="3.24"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="navigateTobasketpage" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.navigateTobasketpage(Money_Control_L1_TestCases.java:137)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigateTobasketpage -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Home_menu" time="0.004">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Home_menu(Money_Control_L1_TestCases.java:151)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Home_menu -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Click_on_Home" time="3.136"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="navigateToHomePage" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.navigateToHomePage(Money_Control_L1_TestCases.java:191)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigateToHomePage -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="new_arrival_is_present" time="3.159"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="seleniumu_Ruby_is_present" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.seleniumu_Ruby_is_present(Money_Control_L1_TestCases.java:222)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- seleniumu_Ruby_is_present -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="one_product_isClickable" time="2.937"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="navigates_to_Selenium_Ruby" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.navigates_to_Selenium_Ruby(Money_Control_L1_TestCases.java:263)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigates_to_Selenium_Ruby -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="add_to_basket" time="3.157"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Click_on_add_to_basket" time="3.176"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="verify_message" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.verify_message(Money_Control_L1_TestCases.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verify_message -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="GoToCart" time="3.16"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="CheckItem" time="0.005">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.CheckItem(Money_Control_L1_TestCases.java:350)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- CheckItem -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Apply_Coupon" time="3.067"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Price_Defined" time="0.003">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Price_Defined(Money_Control_L1_TestCases.java:386)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Price_Defined -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Price_Defined_in_correct_Format" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Price_Defined_in_correct_Format(Money_Control_L1_TestCases.java:404)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Price_Defined_in_correct_Format -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Quantity_Defined" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Quantity_Defined(Money_Control_L1_TestCases.java:422)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Quantity_Defined -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="quantity_Defined_in_correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.quantity_Defined_in_correct_Format(Money_Control_L1_TestCases.java:439)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- quantity_Defined_in_correct_Format -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Total_Defined" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Total_Defined(Money_Control_L1_TestCases.java:456)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Total_Defined -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Total_Defined_in_Correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Total_Defined_in_Correct_Format(Money_Control_L1_TestCases.java:473)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Total_Defined_in_Correct_Format -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Tax_Defined" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Tax_Defined(Money_Control_L1_TestCases.java:489)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Tax_Defined -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Tax_Defined_in_correct_Format" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Tax_Defined_in_correct_Format(Money_Control_L1_TestCases.java:506)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Tax_Defined_in_correct_Format -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="remove_option_is_present" time="3.205"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="remove" time="3.171"/>
  <testcase classname="testcases.Money_Control_L1_TestCases" name="ValidateAnRemoveMessage" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.ValidateAnRemoveMessage(Money_Control_L1_TestCases.java:563)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ValidateAnRemoveMessage -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="updateQuantity" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.updateQuantity(Money_Control_L1_TestCases.java:578)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- updateQuantity -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Update_Basket" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Update_Basket(Money_Control_L1_TestCases.java:595)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Update_Basket -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Proceed_to_checkout" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Proceed_to_checkout(Money_Control_L1_TestCases.java:613)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Proceed_to_checkout -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="Click_Proceed_to_checkout" time="0.002">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at testcases.Money_Control_L1_TestCases.Click_Proceed_to_checkout(Money_Control_L1_TestCases.java:631)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- Click_Proceed_to_checkout -->
  <testcase classname="testcases.Money_Control_L1_TestCases" name="navigate_to_Billing_Details_page" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Money_Control_L1_TestCases.navigate_to_Billing_Details_page(Money_Control_L1_TestCases.java:653)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- navigate_to_Billing_Details_page -->
</testsuite> <!-- Test -->
